project_id = "xopuasvbypkiszcqgdwm"

[functions.parse-loan-document]
verify_jwt = true

[functions.save-draft-application]
verify_jwt = false

[functions.submit-loan-application]
verify_jwt = false

[functions.send-consent-otp]
verify_jwt = false

[functions.verify-consent-otp]
verify_jwt = false
