project_id = "xopuasvbypkiszcqgdwm"

[functions.parse-loan-document]
verify_jwt = true

[functions.save-draft-application]
verify_jwt = false

[functions.submit-loan-application]
verify_jwt = false

[functions.send-consent-otp]
verify_jwt = false

[functions.verify-consent-otp]
verify_jwt = false

[functions.send-public-otp]
verify_jwt = false

[functions.verify-public-otp]
verify_jwt = false

[functions.verify-public-pan]
verify_jwt = false

[functions.sandbox-authenticate]
verify_jwt = false

[functions.parse-pan-document]
verify_jwt = false

[functions.esign-verify-token]
verify_jwt = false

[functions.esign-initiate-aadhaar]
verify_jwt = false

[functions.esign-complete-sign]
verify_jwt = false
